projects:
  Floky:
    schemaPath: amplify/backend/api/Floky/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/API.service.ts
        docsFilePath: src/graphql
        region: us-west-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
