import { ActivityLevel, ActivityType } from "src/contexts/shared/domain/models";
import { inputActivity } from "./root";
import { topicsCreated } from "./topics";

export const activitiesToLoad: inputActivity[] = [

    //============================================================
    // "name": "Saludos y despedidas",
    //============================================================

    // hola
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "HOLA", question: "Ves a tu compañero de clases", questionBody: "¿Cómo lo saludas?", answers: { correct: "Hello", incorrect_1: "Hola", incorrect_2: "Gelow", incorrect_3: "Good night", pronunciation: "həˈlō", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "HOLA", question: "Ves a tu compañero de clases", questionBody: "¿Cómo lo saludas?", answers: { correct: "Hello", incorrect_1: "Hola", incorrect_2: "Gelow", incorrect_3: "Good night", pronunciation: "həˈlō", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "HOLA", question: "Ves a tu compañero de clases", questionBody: "¿Cómo lo saludas?", answers: { correct: "Hello", incorrect_1: "Hola", incorrect_2: "Gelow", incorrect_3: "Good night", pronunciation: "həˈlō", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "HOLA", question: "Ves a tu compañero de clases", questionBody: "¿Cómo lo saludas?", answers: { correct: "Hello", incorrect_1: "Hola", incorrect_2: "Gelow", incorrect_3: "Good night", pronunciation: "həˈlō", } },

    // good morning
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Buenos días", question: "Tu profesor pregunta, ¿Cómo se dice 'buenos días' en inglés?", questionBody: "¿Cómo respondes?", answers: { correct: "Good morning", incorrect_1: "Hola", incorrect_2: "Buenas", incorrect_3: "Good night", pronunciation: "ɡo͝od ˈmôrniNG", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Buenos días", question: "Tu profesor pregunta, ¿Cómo se dice 'buenos días' en inglés?", questionBody: "¿Cómo respondes?", answers: { correct: "Good morning", incorrect_1: "Hola", incorrect_2: "Buenas", incorrect_3: "Good night", pronunciation: "ɡo͝od ˈmôrniNG", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Buenos días", question: "Tu profesor pregunta, ¿Cómo se dice 'buenos días' en inglés?", questionBody: "¿Cómo respondes?", answers: { correct: "Good morning", incorrect_1: "Hola", incorrect_2: "Buenas", incorrect_3: "Good night", pronunciation: "ɡo͝od ˈmôrniNG", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Buenos días", question: "Tu profesor pregunta, ¿Cómo se dice 'buenos días' en inglés?", questionBody: "¿Cómo respondes?", answers: { correct: "Good morning", incorrect_1: "Hola", incorrect_2: "Buenas", incorrect_3: "Good night", pronunciation: "ɡo͝od ˈmôrniNG", } },

    // que bueno verte
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Que bueno verte", question: "Te casas y tu amiga va a la boda", questionBody: "¿Cómo la saludas?", answers: { correct: "Good to see you", incorrect_1: "My gift?", incorrect_2: "Gracias por venir", incorrect_3: "You will love the dinner", pronunciation: "ɡo͝od to͞o sē yo͞o", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Que bueno verte", question: "Te casas y tu amiga va a la boda", questionBody: "¿Cómo la saludas?", answers: { correct: "Good to see you", incorrect_1: "My gift?", incorrect_2: "Gracias por venir", incorrect_3: "You will love the dinner", pronunciation: "ɡo͝od to͞o sē yo͞o", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Que bueno verte", question: "Te casas y tu amiga va a la boda", questionBody: "¿Cómo la saludas?", answers: { correct: "Good to see you", incorrect_1: "My gift?", incorrect_2: "Gracias por venir", incorrect_3: "You will love the dinner", pronunciation: "ɡo͝od to͞o sē yo͞o", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[0], activityTopicId: topicsCreated[0].id, name: "Que bueno verte", question: "Te casas y tu amiga va a la boda", questionBody: "¿Cómo la saludas?", answers: { correct: "Good to see you", incorrect_1: "My gift?", incorrect_2: "Gracias por venir", incorrect_3: "You will love the dinner", pronunciation: "ɡo͝od to͞o sē yo͞o", } },

    //============================================================
    // "name": "Lugar donde vivimos",
    //============================================================
    // Aeropuerto
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Aeropuerto", question: "Los aviones despegan y aterrizan allí.", questionBody: "¿Qué es eso?", answers: { correct: "Airport", incorrect_1: "Airpor", incorrect_2: "Aiport", incorrect_3: "iirport", pronunciation: "ehr-port", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Aeropuerto", question: "Los aviones despegan y aterrizan allí.", questionBody: "¿Qué es eso?", answers: { correct: "Airport", incorrect_1: "Airpor", incorrect_2: "Aiport", incorrect_3: "iirport", pronunciation: "ehr-port", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Aeropuerto", question: "Los aviones despegan y aterrizan allí.", questionBody: "¿Qué es eso?", answers: { correct: "Airport", incorrect_1: "Airpor", incorrect_2: "Aiport", incorrect_3: "iirport", pronunciation: "ehr-port", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Aeropuerto", question: "Los aviones despegan y aterrizan allí.", questionBody: "¿Qué es eso?", answers: { correct: "Airport", incorrect_1: "Airpor", incorrect_2: "Aiport", incorrect_3: "iirport", pronunciation: "ehr-port", } },
    // Antiguo
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Antiguo", question: "La casa de mi abuela tiene 100 años de antigüedad.", questionBody: "La casa de mi abuela es...", answers: { correct: "Ancient", incorrect_1: "Ancien", incorrect_2: "Ancint", incorrect_3: "Anient", pronunciation: "eyn-chihnt", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Antiguo", question: "La casa de mi abuela tiene 100 años de antigüedad.", questionBody: "La casa de mi abuela es...", answers: { correct: "Ancient", incorrect_1: "Ancien", incorrect_2: "Ancint", incorrect_3: "Anient", pronunciation: "eyn-chihnt", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Antiguo", question: "La casa de mi abuela tiene 100 años de antigüedad.", questionBody: "La casa de mi abuela es...", answers: { correct: "Ancient", incorrect_1: "Ancien", incorrect_2: "Ancint", incorrect_3: "Anient", pronunciation: "eyn-chihnt", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Antiguo", question: "La casa de mi abuela tiene 100 años de antigüedad.", questionBody: "La casa de mi abuela es...", answers: { correct: "Ancient", incorrect_1: "Ancien", incorrect_2: "Ancint", incorrect_3: "Anient", pronunciation: "eyn-chihnt", } },
    // Avenida
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Avenida", question: "La avenida 'San Pedro' es la mas grande de mi ciudad.", questionBody: "San Pedro a___e is the largest in my city.", answers: { correct: "Avenue", incorrect_1: "Aenue", incorrect_2: "avenida", incorrect_3: "Abenue", pronunciation: "ah-vih-nu", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Avenida", question: "La avenida 'San Pedro' es la mas grande de mi ciudad.", questionBody: "San Pedro a___e is the largest in my city.", answers: { correct: "Avenue", incorrect_1: "Aenue", incorrect_2: "avenida", incorrect_3: "Abenue", pronunciation: "ah-vih-nu", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Avenida", question: "La avenida 'San Pedro' es la mas grande de mi ciudad.", questionBody: "San Pedro a___e is the largest in my city.", answers: { correct: "Avenue", incorrect_1: "Aenue", incorrect_2: "avenida", incorrect_3: "Abenue", pronunciation: "ah-vih-nu", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "Avenida", question: "La avenida 'San Pedro' es la mas grande de mi ciudad.", questionBody: "San Pedro a___e is the largest in my city.", answers: { correct: "Avenue", incorrect_1: "Aenue", incorrect_2: "avenida", incorrect_3: "Abenue", pronunciation: "ah-vih-nu", } },

    //============================================================
    // name: "Yo y mi familia",
    //============================================================
    // Tía
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Tía", question: "Ella es la hermana de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "aunt", incorrect_1: "aont", incorrect_2: "aint", incorrect_3: "aent", pronunciation: "ahnt", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Tía", question: "Ella es la hermana de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "aunt", incorrect_1: "aont", incorrect_2: "aint", incorrect_3: "aent", pronunciation: "ahnt", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Tía", question: "Ella es la hermana de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "aunt", incorrect_1: "aont", incorrect_2: "aint", incorrect_3: "aent", pronunciation: "ahnt", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Tía", question: "Ella es la hermana de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "aunt", incorrect_1: "aont", incorrect_2: "aint", incorrect_3: "aent", pronunciation: "ahnt", } },
    // Primo
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Primo", question: "Es el hijo de mi tío.", questionBody: "¿Quién es él?", answers: { correct: "cousin", incorrect_1: "couson", incorrect_2: "cousyn", incorrect_3: "cousan", pronunciation: "kuh-zihn", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Primo", question: "Es el hijo de mi tío.", questionBody: "¿Quién es él?", answers: { correct: "cousin", incorrect_1: "couson", incorrect_2: "cousyn", incorrect_3: "cousan", pronunciation: "kuh-zihn", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Primo", question: "Es el hijo de mi tío.", questionBody: "¿Quién es él?", answers: { correct: "cousin", incorrect_1: "couson", incorrect_2: "cousyn", incorrect_3: "cousan", pronunciation: "kuh-zihn", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Primo", question: "Es el hijo de mi tío.", questionBody: "¿Quién es él?", answers: { correct: "cousin", incorrect_1: "couson", incorrect_2: "cousyn", incorrect_3: "cousan", pronunciation: "kuh-zihn", } },
    // Abuela
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Abuela", question: "Ella es la mamá de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "grandmother", incorrect_1: "grantmother", incorrect_2: "grondmother", incorrect_3: "grandmoter", pronunciation: "grahn-muh-thuhr", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Abuela", question: "Ella es la mamá de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "grandmother", incorrect_1: "grantmother", incorrect_2: "grondmother", incorrect_3: "grandmoter", pronunciation: "grahn-muh-thuhr", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Abuela", question: "Ella es la mamá de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "grandmother", incorrect_1: "grantmother", incorrect_2: "grondmother", incorrect_3: "grandmoter", pronunciation: "grahn-muh-thuhr", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[2], activityTopicId: topicsCreated[2].id, name: "Abuela", question: "Ella es la mamá de mi mamá.", questionBody: "¿Quién es ella?", answers: { correct: "grandmother", incorrect_1: "grantmother", incorrect_2: "grondmother", incorrect_3: "grandmoter", pronunciation: "grahn-muh-thuhr", } },

    //============================================================
    // name: "Clima"
    //============================================================
    // fog
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Niebla", question: "This morning there was a lot of f_g.", questionBody: "What was a lot in the morning?", answers: { correct: "Fog", incorrect_1: "gof", incorrect_2: "fug", incorrect_3: "guf", pronunciation: "fôɡ", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Niebla", question: "This morning there was a lot of f_g.", questionBody: "What was a lot in the morning?", answers: { correct: "Fog", incorrect_1: "gof", incorrect_2: "fug", incorrect_3: "guf", pronunciation: "fôɡ", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Niebla", question: "This morning there was a lot of f_g.", questionBody: "What was a lot in the morning?", answers: { correct: "Fog", incorrect_1: "gof", incorrect_2: "fug", incorrect_3: "guf", pronunciation: "fôɡ", } },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Niebla", question: "This morning there was a lot of f_g.", questionBody: "What was a lot in the morning?", answers: { correct: "Fog", incorrect_1: "gof", incorrect_2: "fug", incorrect_3: "guf", pronunciation: "fôɡ", } },
    // rain
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "La lluvia va a empezar", question: "The r__n is going to start", questionBody: "What is going to start?", answers: { correct: "rain", incorrect_1: "rian", incorrect_2: "raan", incorrect_3: "ruin", pronunciation: "rān", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "La lluvia va a empezar", question: "The r__n is going to start", questionBody: "What is going to start?", answers: { correct: "rain", incorrect_1: "rian", incorrect_2: "raan", incorrect_3: "ruin", pronunciation: "rān", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "La lluvia va a empezar", question: "The r__n is going to start", questionBody: "What is going to start?", answers: { correct: "rain", incorrect_1: "rian", incorrect_2: "raan", incorrect_3: "ruin", pronunciation: "rān", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "La lluvia va a empezar", question: "The r__n is going to start", questionBody: "What is going to start?", answers: { correct: "rain", incorrect_1: "rian", incorrect_2: "raan", incorrect_3: "ruin", pronunciation: "rān", }, },
    // humidity
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Humedad en el clima", question: "No me gusta la humedad.", questionBody: "En Inglés se diría 'I don't like the h______y of this climate'.", answers: { correct: "Humidity", incorrect_1: "humiditi", incorrect_2: "homidity", incorrect_3: "hamidity", pronunciation: "(h)yo͞oˈmidədē", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Humedad en el clima", question: "No me gusta la humedad.", questionBody: "En Inglés se diría 'I don't like the h______y of this climate'.", answers: { correct: "Humidity", incorrect_1: "humiditi", incorrect_2: "homidity", incorrect_3: "hamidity", pronunciation: "(h)yo͞oˈmidədē", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Humedad en el clima", question: "No me gusta la humedad.", questionBody: "En Inglés se diría 'I don't like the h______y of this climate'.", answers: { correct: "Humidity", incorrect_1: "humiditi", incorrect_2: "homidity", incorrect_3: "hamidity", pronunciation: "(h)yo͞oˈmidədē", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[3], activityTopicId: topicsCreated[3].id, name: "Humedad en el clima", question: "No me gusta la humedad.", questionBody: "En Inglés se diría 'I don't like the h______y of this climate'.", answers: { correct: "Humidity", incorrect_1: "humiditi", incorrect_2: "homidity", incorrect_3: "hamidity", pronunciation: "(h)yo͞oˈmidədē", }, },

    //============================================================
    // name: "Enfermedades"
    //============================================================
    // Sneezes
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Mi papá estornuda muy fuerte", question: "Mi papá estornuda muy fuerte. Esto es ingles se dice", questionBody: "My dad sn___es very loudly.", answers: { correct: "Sneezes", incorrect_1: "Sneezzes", incorrect_2: "Snezes", incorrect_3: "Sneeses", pronunciation: "snēz", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Mi papá estornuda muy fuerte", question: "Mi papá estornuda muy fuerte. Esto es ingles se dice", questionBody: "My dad sn___es very loudly.", answers: { correct: "Sneezes", incorrect_1: "Sneezzes", incorrect_2: "Snezes", incorrect_3: "Sneeses", pronunciation: "snēz", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Mi papá estornuda muy fuerte", question: "Mi papá estornuda muy fuerte. Esto es ingles se dice", questionBody: "My dad sn___es very loudly.", answers: { correct: "Sneezes", incorrect_1: "Sneezzes", incorrect_2: "Snezes", incorrect_3: "Sneeses", pronunciation: "snēz", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Mi papá estornuda muy fuerte", question: "Mi papá estornuda muy fuerte. Esto es ingles se dice", questionBody: "My dad sn___es very loudly.", answers: { correct: "Sneezes", incorrect_1: "Sneezzes", incorrect_2: "Snezes", incorrect_3: "Sneeses", pronunciation: "snēz", }, },
    // Ear Ache
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Dolor de oido", question: "Mi hijo tiene dolor de oído. Para decírselo a un médico en inglés decimos...", questionBody: "My son have e_r a__e.", answers: { correct: "Ear ache", incorrect_1: "Eer ache", incorrect_2: "Ear akke", incorrect_3: "Ear ahce", pronunciation: "ˈirˌāk", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Dolor de oido", question: "Mi hijo tiene dolor de oído. Para decírselo a un médico en inglés decimos...", questionBody: "My son have e_r a__e.", answers: { correct: "Ear ache", incorrect_1: "Eer ache", incorrect_2: "Ear akke", incorrect_3: "Ear ahce", pronunciation: "ˈirˌāk", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Dolor de oido", question: "Mi hijo tiene dolor de oído. Para decírselo a un médico en inglés decimos...", questionBody: "My son have e_r a__e.", answers: { correct: "Ear ache", incorrect_1: "Eer ache", incorrect_2: "Ear akke", incorrect_3: "Ear ahce", pronunciation: "ˈirˌāk", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Dolor de oido", question: "Mi hijo tiene dolor de oído. Para decírselo a un médico en inglés decimos...", questionBody: "My son have e_r a__e.", answers: { correct: "Ear ache", incorrect_1: "Eer ache", incorrect_2: "Ear akke", incorrect_3: "Ear ahce", pronunciation: "ˈirˌāk", }, },
    // Fiebre : Fever
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Tengo fiebre", question: "Para decírle a un médico que 'Tengo fiebre' en inglés decimos...", questionBody: "I have f___r", answers: { correct: "Fever", incorrect_1: "Feeer", incorrect_2: "Feber", incorrect_3: "Gever", pronunciation: "ˈfēvər", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.READING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Tengo fiebre", question: "Para decírle a un médico que 'Tengo fiebre' en inglés decimos...", questionBody: "I have f___r", answers: { correct: "Fever", incorrect_1: "Feeer", incorrect_2: "Feber", incorrect_3: "Gever", pronunciation: "ˈfēvər", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.TALKING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Tengo fiebre", question: "Para decírle a un médico que 'Tengo fiebre' en inglés decimos...", questionBody: "I have f___r", answers: { correct: "Fever", incorrect_1: "Feeer", incorrect_2: "Feber", incorrect_3: "Gever", pronunciation: "ˈfēvər", }, },
    { activityLevel: ActivityLevel.A1, activityType: ActivityType.LISTENING, topic: topicsCreated[4], activityTopicId: topicsCreated[4].id, name: "Tengo fiebre", question: "Para decírle a un médico que 'Tengo fiebre' en inglés decimos...", questionBody: "I have f___r", answers: { correct: "Fever", incorrect_1: "Feeer", incorrect_2: "Feber", incorrect_3: "Gever", pronunciation: "ˈfēvər", }, },

    //============================================================
    // name: "Hablar en el trabajo",
    //============================================================
    // internship - pasantía",
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.WRITING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Deseo tener una pasantía.", question: "Deseo tener una pasantía en esta empresa desde que comence a estudiar.", questionBody: "What do I wish to get?", answers: { correct: "Internship", incorrect_1: "Intternship", incorrect_2: "Internshipp", incorrect_3: "Internshyp", pronunciation: "in·trn·shuhp", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.READING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Deseo tener una pasantía.", question: "Deseo tener una pasantía en esta empresa desde que comence a estudiar.", questionBody: "What do I wish to get?", answers: { correct: "Internship", incorrect_1: "Intternship", incorrect_2: "Internshipp", incorrect_3: "Internshyp", pronunciation: "in·trn·shuhp", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.TALKING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Deseo tener una pasantía.", question: "Deseo tener una pasantía en esta empresa desde que comence a estudiar.", questionBody: "What do I wish to get?", answers: { correct: "Internship", incorrect_1: "Intternship", incorrect_2: "Internshipp", incorrect_3: "Internshyp", pronunciation: "in·trn·shuhp", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.LISTENING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Deseo tener una pasantía.", question: "Deseo tener una pasantía en esta empresa desde que comence a estudiar.", questionBody: "What do I wish to get?", answers: { correct: "Internship", incorrect_1: "Intternship", incorrect_2: "Internshipp", incorrect_3: "Internshyp", pronunciation: "in·trn·shuhp", }, },
    // "part-time job - trabajo de media jornada",
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.WRITING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Trabajo de medio tiempo", question: "Hector tiene un trabajo de medio tiempo.", questionBody: "What kind of job does Hector have?", answers: { correct: "Part time job", incorrect_1: "Half job", incorrect_2: "Half time job", incorrect_3: "Middle time job", pronunciation: "", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.READING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Trabajo de medio tiempo", question: "Hector tiene un trabajo de medio tiempo.", questionBody: "What kind of job does Hector have?", answers: { correct: "Part time job", incorrect_1: "Half job", incorrect_2: "Half time job", incorrect_3: "Middle time job", pronunciation: "", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.TALKING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Trabajo de medio tiempo", question: "Hector tiene un trabajo de medio tiempo.", questionBody: "What kind of job does Hector have?", answers: { correct: "Part time job", incorrect_1: "Half job", incorrect_2: "Half time job", incorrect_3: "Middle time job", pronunciation: "", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.LISTENING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Trabajo de medio tiempo", question: "Hector tiene un trabajo de medio tiempo.", questionBody: "What kind of job does Hector have?", answers: { correct: "Part time job", incorrect_1: "Half job", incorrect_2: "Half time job", incorrect_3: "Middle time job", pronunciation: "", }, },
    // "Day shift - turno de día",
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.WRITING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Turno de día", question: "Mi novio trabaja de cajero unicamente en el turno de dia.", questionBody: "My boyfriend has ___ _____.", answers: { correct: "Day shift", incorrect_1: "Day shiff", incorrect_2: "Day shoft", incorrect_3: "Day shuft", pronunciation: "ˈdā ˌSHift", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.READING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Turno de día", question: "Mi novio trabaja de cajero unicamente en el turno de dia.", questionBody: "My boyfriend has ___ _____.", answers: { correct: "Day shift", incorrect_1: "Day shiff", incorrect_2: "Day shoft", incorrect_3: "Day shuft", pronunciation: "ˈdā ˌSHift", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.TALKING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Turno de día", question: "Mi novio trabaja de cajero unicamente en el turno de dia.", questionBody: "My boyfriend has ___ _____.", answers: { correct: "Day shift", incorrect_1: "Day shiff", incorrect_2: "Day shoft", incorrect_3: "Day shuft", pronunciation: "ˈdā ˌSHift", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.LISTENING, topic: topicsCreated[5], activityTopicId: topicsCreated[5].id, name: "Turno de día", question: "Mi novio trabaja de cajero unicamente en el turno de dia.", questionBody: "My boyfriend has ___ _____.", answers: { correct: "Day shift", incorrect_1: "Day shiff", incorrect_2: "Day shoft", incorrect_3: "Day shuft", pronunciation: "ˈdā ˌSHift", }, },

    //============================================================
    // name: "Frases y expresiones",
    //============================================================
    //take it easy
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.WRITING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Tomalo con calma", question: "Me moleste con él y me dijo 'Tomalo con calma'", questionBody: "He said 'tak_ __ _asy'.", answers: { correct: "Take it easy", incorrect_1: "Tako it easy", incorrect_2: "Take at easy", incorrect_3: "Taked it easy", pronunciation: "teyk iht i-zi", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.READING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Tomalo con calma", question: "Me moleste con él y me dijo 'Tomalo con calma'", questionBody: "He said 'tak_ __ _asy'.", answers: { correct: "Take it easy", incorrect_1: "Tako it easy", incorrect_2: "Take at easy", incorrect_3: "Taked it easy", pronunciation: "teyk iht i-zi", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.TALKING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Tomalo con calma", question: "Me moleste con él y me dijo 'Tomalo con calma'", questionBody: "He said 'tak_ __ _asy'.", answers: { correct: "Take it easy", incorrect_1: "Tako it easy", incorrect_2: "Take at easy", incorrect_3: "Taked it easy", pronunciation: "teyk iht i-zi", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.LISTENING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Tomalo con calma", question: "Me moleste con él y me dijo 'Tomalo con calma'", questionBody: "He said 'tak_ __ _asy'.", answers: { correct: "Take it easy", incorrect_1: "Tako it easy", incorrect_2: "Take at easy", incorrect_3: "Taked it easy", pronunciation: "teyk iht i-zi", }, },
    // "Really?. (¿En serio?)"
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.WRITING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "No te creo.", question: "¿En serio? ¿Has terminado tu tesis?", questionBody: "R____y? Have you finished your thesis?.", answers: { correct: "Really", incorrect_1: "Realy", incorrect_2: "Relly", incorrect_3: "Rally", pronunciation: "ˈrē(ə)lē", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.READING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "No te creo.", question: "¿En serio? ¿Has terminado tu tesis?", questionBody: "R____y? Have you finished your thesis?.", answers: { correct: "Really", incorrect_1: "Realy", incorrect_2: "Relly", incorrect_3: "Rally", pronunciation: "ˈrē(ə)lē", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.TALKING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "No te creo.", question: "¿En serio? ¿Has terminado tu tesis?", questionBody: "R____y? Have you finished your thesis?.", answers: { correct: "Really", incorrect_1: "Realy", incorrect_2: "Relly", incorrect_3: "Rally", pronunciation: "ˈrē(ə)lē", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.LISTENING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "No te creo.", question: "¿En serio? ¿Has terminado tu tesis?", questionBody: "R____y? Have you finished your thesis?.", answers: { correct: "Really", incorrect_1: "Realy", incorrect_2: "Relly", incorrect_3: "Rally", pronunciation: "ˈrē(ə)lē", }, },
    // Toco madera
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.WRITING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Toco madera", question: "Toco madera. Por si acaso.", questionBody: "I hit lightly wood.. Jus_ __ _ase.", answers: { correct: "Just in case", incorrect_1: "Just on case", incorrect_2: "Juss in case", incorrect_3: "Just in kase", pronunciation: "juhst ihn keys", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.READING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Toco madera", question: "Toco madera. Por si acaso.", questionBody: "I hit lightly wood.. Jus_ __ _ase.", answers: { correct: "Just in case", incorrect_1: "Just on case", incorrect_2: "Juss in case", incorrect_3: "Just in kase", pronunciation: "juhst ihn keys", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.TALKING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Toco madera", question: "Toco madera. Por si acaso.", questionBody: "I hit lightly wood.. Jus_ __ _ase.", answers: { correct: "Just in case", incorrect_1: "Just on case", incorrect_2: "Juss in case", incorrect_3: "Just in kase", pronunciation: "juhst ihn keys", }, },
    { activityLevel: ActivityLevel.A2, activityType: ActivityType.LISTENING, topic: topicsCreated[6], activityTopicId: topicsCreated[6].id, name: "Toco madera", question: "Toco madera. Por si acaso.", questionBody: "I hit lightly wood.. Jus_ __ _ase.", answers: { correct: "Just in case", incorrect_1: "Just on case", incorrect_2: "Juss in case", incorrect_3: "Just in kase", pronunciation: "juhst ihn keys", }, },



];


// { correct: "", incorrect_1: "", incorrect_2: "", incorrect_3: "", pronunciation: "", }







//============================================================
// "name": "Lugar donde vivimos",
//============================================================
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Bakery", incorrect_1: "Bakeri", incorrect_2: "Baquery", incorrect_3: "vaquero", pronunciation: "bey-kuh-ri", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Bank", incorrect_1: "Bankk", incorrect_2: "Banq", incorrect_3: "vank", pronunciation: "beyngk", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Beautiful", incorrect_1: "Beautifull", incorrect_2: "Beauttiful", incorrect_3: "Beeutiful", pronunciation: "byu-dih-fuhl", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Big", incorrect_1: "Bij", incorrect_2: "vig", incorrect_3: "Biq", pronunciation: "big", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Boring", incorrect_1: "Borring", incorrect_2: "Buring", incorrect_3: "Voring", pronunciation: "baw-rihng", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Bus station", incorrect_1: "police station", incorrect_2: "Busy station", incorrect_3: "Boring station", pronunciation: "buhs stey-shihn", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Bus stop", incorrect_1: "Bus red", incorrect_2: "stop", incorrect_3: "Bus estop", pronunciation: "buhs stap", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Busy", incorrect_1: "Busi", incorrect_2: "Bosy", incorrect_3: "Bucy", pronunciation: "bih-zi", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Butcher", incorrect_1: "Butcherr", incorrect_2: "Buttcher", incorrect_3: "Vutcher", pronunciation: "booch-uhr", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Calm", incorrect_1: "Calmp", incorrect_2: "Camp", incorrect_3: "Call", pronunciation: "kam", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Car park", incorrect_1: "Car park", incorrect_2: "Car parq", incorrect_3: "Car parque", pronunciation: "kar park", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Cheap", incorrect_1: "Chip", incorrect_2: "Cheep", incorrect_3: "Chaap", pronunciation: "chip", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Church", incorrect_1: "Churc", incorrect_2: "Churq", incorrect_3: "Chorch", pronunciation: "chuhrch", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Cinema", incorrect_1: "Cine", incorrect_2: "Sinema", incorrect_3: "autocinema", pronunciation: "sɪ-nə-mə", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Crowded", incorrect_1: "Crowdeed", incorrect_2: "Cruwded", incorrect_3: "Croowded", pronunciation: "kɹaʊ-dɪd", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Exciting", incorrect_1: "Excitinq", incorrect_2: "Exiting", incorrect_3: "Excitynq", pronunciation: "ehk-say-dihng", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Expensive", incorrect_1: "Expensivy", incorrect_2: "Espensive", incorrect_3: "Expeensive", pronunciation: "ehk-spehn-sihv", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Fire station", incorrect_1: "Firee station", incorrect_2: "Fyre station", incorrect_3: "Fore station", pronunciation: "fay-er stey-shihn", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Grocery", incorrect_1: "Groceri", incorrect_2: "Groocery", incorrect_3: "Grucery", pronunciation: "gro-suh-ri", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Gym", incorrect_1: "Gim", incorrect_2: "Jym", incorrect_3: "Jam", pronunciation: "jihm", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Hairdressers", incorrect_1: "Hairdresserss", incorrect_2: "Heirdressers", incorrect_3: "Jairdressers", pronunciation: "hehr-drehs-uhr", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Huge", incorrect_1: "Hugge", incorrect_2: "Hugi", incorrect_3: "Hoge", pronunciation: "hyuj", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Interesting", incorrect_1: "Interestyng", incorrect_2: "Interresting", incorrect_3: "Interessting", pronunciation: "ihn-trihs-tihng", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Modern", incorrect_1: "Mudern", incorrect_2: "Moddern", incorrect_3: "Moderrn", pronunciation: "ma-duhrn", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Pavement", incorrect_1: "Pavementt", incorrect_2: "Pavemennt", incorrect_3: "Pavvement", pronunciation: "peyv-mihnt", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Pharmacy", incorrect_1: "Phermacy", incorrect_2: "Pharmasy", incorrect_3: "Parmacy", pronunciation: "far-muh-si", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Polluted", incorrect_1: "Pollutedd", incorrect_2: "Poyuted", incorrect_3: "Pullutid", pronunciation: "puh-lu-dihd", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Post office", incorrect_1: "Post ofice", incorrect_2: "Pust office", incorrect_3: "Poss office", pronunciation: "post a-fihs", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Quiet", incorrect_1: "Quit", incorrect_2: "Quet", incorrect_3: "Quiit", pronunciation: "kway-iht", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Road", incorrect_1: "Ruad", incorrect_2: "Roed", incorrect_3: "Roag", pronunciation: "rod", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Small", incorrect_1: "Smull", incorrect_2: "Smaq", incorrect_3: "Smoll", pronunciation: "smal", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Square", incorrect_1: "Squary", incorrect_2: "Squore", incorrect_3: "Sguare", pronunciation: "skwehr", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Street", incorrect_1: "Stret", incorrect_2: "Streat", incorrect_3: "Streot", pronunciation: "strit", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Tailors", incorrect_1: "Tailoos", incorrect_2: "Tilors", incorrect_3: "Tailurs", pronunciation: "tey-luhr", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Town hall", incorrect_1: "Town holl", incorrect_2: "Town hull", incorrect_3: "Tawn hall", pronunciation: "taun hal", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Traffic light", incorrect_1: "Traffic loght", incorrect_2: "Traffic lyght", incorrect_3: "Traffic laght", pronunciation: "trah-fihk layt", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Train station", incorrect_1: "Train staton", incorrect_2: "Train stition", incorrect_3: "Trein station", pronunciation: "treyn stey-shihn", } },
// { activityLevel: ActivityLevel.A1, activityType: ActivityType.WRITING, topic: topicsCreated[1], activityTopicId: topicsCreated[1].id, name: "", question: "", questionBody: "",  answers: { correct: "Unpleasant", incorrect_1: "Unpleasantt", incorrect_2: "Unpleeasant", incorrect_3: "Unpleasaant", pronunciation: "uhn-plehz-ihnt", } },/hjuːˈmɪd.ə.t̬i/